# Generated by Django 2.2 on 2020-12-08 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0002_auto_20201208_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cookbook_id',
        ),
    ]
